/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usbbog.co.peluquerias.inicio;

import controladores.TipoJpaController;
import controladores.UsuarioJpaController;
import entidades.Tipo;
import entidades.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author orion
 */
public class Inicio extends javax.swing.JFrame {
TipoJpaController Ctipo =  new TipoJpaController();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        CrearModelo2();

    }

    
    
    
    DefaultTableModel modelo2;

    private void CrearModelo2() {
        try {
            modelo2 = (new DefaultTableModel(
                    null, new String[]{
                        "id_tipo", "Detalle"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class

                };
                boolean[] canEdit = new boolean[]{
                    false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            table.setModel(modelo2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }
 
 
  private void Cargar_Informacion(){
   try{
       Object o[]=null;
       
       List<Tipo> listP = Ctipo.findTipoEntities();
       for(int i=0;i< listP.size();i++){
           
          modelo2.addRow(o);
          modelo2.setValueAt(listP.get(i).getIdTipo(), i,0);
          modelo2.setValueAt(listP.get(i).getDetalle(), i,1);
          
           
       }
       
       
       
   }     
   catch(Exception e){
   
   JOptionPane.showInternalMessageDialog(null, e.getMessage());
   }     
    
  }
    

    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        detalle = new javax.swing.JTextField();
        REGISTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 340, 360));

        jLabel2.setText("DESCRIPCION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                detalleKeyTyped(evt);
            }
        });
        getContentPane().add(detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        REGISTRAR.setText("REGISTRAR");
        REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(REGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detalleKeyTyped
char c = evt.getKeyChar();
if((c<'a'||c>'z')&&(c<'A'||c>'Z'))  evt.consume();

    }//GEN-LAST:event_detalleKeyTyped

    private void REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARActionPerformed
        try {
            Tipo T = new Tipo();

            // T.setIdTipo(Integer.parseInt(id_type.getText()));
            T.setDetalle(detalle.getText());

            Ctipo.create(T);

            JOptionPane.showMessageDialog(null, "DATOS GUARDADOS CON EXITO");
            Cargar_Informacion();
        }

        catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_REGISTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

 
 
 
 
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGISTRAR;
    private javax.swing.JTextField detalle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
